---
- hosts: server
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install docker
    apt:
      name: docker
      state: latest
  
  - name: install docker-compose
    apt:
      name: docker-compose
      state: latest

  - name: make prometheus dir
    file:
      path: /opt/Mr-Labkit/prometheus/server
      state: directory
      recurse: yes
  
  - name: copy files
    copy:
      src: "{{ item }}"
      dest: /opt/Mr-Labkit/prometheus/server
    with_fileglob:
    - "prometheus/server/*"

  - name: run prometheus container
    shell: docker-compose up -d chdir=/opt/Mr-Labkit/prometheus/server
