---
- hosts: client
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install docker
    apt:
      name: 
      - docker
      - docker-compose
      state: latest

  - name: chmod "{{ user }} -aG docker"
    user:
      name: "{{ user }}"
      state: latest
      groups:
      - docker
      append: yes
  
  - name: make prometheus dir
    file:
      path: /opt/Mr-Labkit/prometheus/client
      state: directory
      recurse: yes

  - name: cp docker-compose.yml
    copy:
      src: prometheus/client/docker-compose.yml
      dest: /opt/Mr-Labkit/prometheus/client

  - name: run prometheus container
    shell: docker-compose up -d chdir=/opt/Mr-Labkit/prometheus/client