---
- hosts: server
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install docker
    apt:
      name: docker
      state: latest
  
  - name: install docker-compose
    apt:
      name: docker-compose
      state: latest
  
  - name: pull ldap image
    shell: docker pull osixia/openldap

  - name: make docker dir
    file:
      path: /opt/Mr-Labkit/ldap
      state: directory

  - name: cp docker-compose
    copy:
      src: ldap/docker-compose.yml
      dest: /opt/Mr-Labkit/ldap/
  
  - name: run ldap container
    shell: docker-compose up -d chdir=/opt/Mr-Labkit/ldap
