---
- hosts: server
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install package
    apt:
      name: 
      - docker
      - docker-compose
      - ldap-utils

  - name: chmod user aG docker
    user:
      name: "{{ user }}"
      state: present
      groups:
      - docker
      append: yes
  
  - name: pull ldap image
    shell: docker pull osixia/openldap

  - name: make docker dir
    file:
      path: /opt/Mr-Labkit/ldap
      state: directory

  - name: cp files
    copy:
      src: "{{ item }}"
      dest: /opt/Mr-Labkit/ldap
    with_fileglob:
    - "ldap/*"

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/ldap
      state: present

  # 後で直す
  - name: sleep
    shell: sleep 5

  - name: ldapadd init
    shell: ldapadd -x -D cn=admin,dc=example,dc=com -w admin -f /opt/Mr-Labkit/ldap/init.ldif
