---
- hosts: k8s_worker
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml
  - vars-k8s.yml

  tasks:
  - name: join cluster
    shell: kubeadm join {{ k8s_masterip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash sha256:{{ hash }}
