Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.ssh.guest_port = 22
    config.ssh.username = "vagrant"
    config.vm.provider "libvirt" do |lv|
        lv.memory = "8192"
        lv.cpus = 4
    end

    # リバースプロキシ
    config.vm.define :rev do |server|
        server.vm.hostname = "rev"
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "{{ revproxyip }}"
    end

    # サーバ
    config.vm.define :s1 do |server|
        server.vm.hostname = "s1"
        server.vm.provider "libvirt" do |lv|
            lv.memory = "16384"
        end
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "{{ serverip }}"
    end

    # ベアメタルのクライアント
    {{ client }}

    # k8sマスター
    config.vm.define :km1 do |server|
        server.vm.hostname = "km1"
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "{{ k8s_masterip }}"
    end

    # k8sワーカー
    {{ k8s_worker }}

end
