- hosts: server
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: cp samba docker
    copy: 
      src: samba/
      dest: /opt/Mr-Labkit/samba/

  - name: make share directory
    file:
      path: /home/lab
      state: directory
      owner: nobody
      group: nogroup
      mode: '0777'
  
  - name: authorization for start.sh
    file:
      path: /opt/Mr-Labkit/samba/start.sh
      mode: a+x
  
  - name: docker build
    docker_image:
      build:
        path: /opt/Mr-Labkit/samba/
      name: samba
      source : build

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/samba/
      state: present
  
  - name: Permission settings for shared directories
    file:
      path: /home/lab/
      mode: "0777"
