---
- hosts: server
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install package
    apt:
      name: 
      - docker
      - docker-compose
      - ldap-utils
      update_cache: yes

  - name: chmod {{ user }} -aG docker
    user:
      name: "{{ user }}"
      state: present
      groups:
      - docker
      append: yes

  - name: make docker dir
    file:
      path: /opt/Mr-Labkit/ldap
      state: directory

  - name: cp files
    copy:
      src: "{{ item }}"
      dest: /opt/Mr-Labkit/ldap
    with_fileglob:
    - "ldap/*"

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/ldap
      state: present

  # 後で直す
  - name: sleep
    command: sleep 5

  # すでにエントリがある場合に"コード68"を返す
  - name: ldapadd init
    command: ldapadd -x -D cn=admin,dc=example,dc=com -w admin -f /opt/Mr-Labkit/ldap/init.ldif
    register: ret
    failed_when: ret.rc not in [0, 68]
