---
- hosts: server
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install docker
    apt:
      name: 
      - docker
      - docker-compose
      state: latest

  - name: make prometheus dir
    file:
      path: /opt/Mr-Labkit/prometheus/server
      state: directory
      recurse: yes
  
  - name: copy files
    copy:
      src: "{{ item }}"
      dest: /opt/Mr-Labkit/prometheus/server
    with_fileglob:
    - "prometheus/server/*"

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/prometheus/server
      state: present
