---
- hosts: all
  gather_facts: yes

  tasks:
  - name: start console
    service:
      name: serial-getty@ttyS0
      state: started
      enabled: yes
  
  - name: delete file
    file:
      path: /etc/netplan/01-netcfg.yaml
      state: absent

  - name: cp /etc/systemd/resolved.conf
    copy:
      src: vagrant/resolved.conf
      dest: /etc/systemd/resolved.conf
  - name:
    command: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

  # - name: 
  #   command: ip addr flush eth0
  # - name: 
  #   command: ip link set eth0 down

  - name:
    shell: cat /etc/netplan/50-vagrant.yaml | grep gateway4
    ignore_errors: yes
    register: ret
  - name: add hosts
    when: ret.rc not in [0]
    lineinfile:
      dest: /etc/netplan/50-vagrant.yaml
      line: "{{ item }}"
    with_items:
    - '      gateway4: 192.168.122.1' # ここを変える
    - '      nameservers:'
    - '        addresses:'
    - '        - 192.168.122.12'
    - '        - 8.8.8.8'
    - '    eth0:'
    - '      dhcp4: no'
  - name:
    command: netplan apply
  - name:
    command: systemctl restart systemd-resolved
