---
- hosts: server
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install NFS
    apt:
      name: nfs-kernel-server
      state: latest

  # - name: starting nfs server
  #   service:
  #     name: nfs-kernel-server
  #     state: enabled
  #     enabled: yes
  
  # 設定ファイルのコピー
  - name: copy files
    copy:
      src: nfs/exports
      dest: /etc/exports
  # 設定ファイルの適用
  - name: export file-system
    command: exportfs -a