- hosts: server
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install package
    apt:
      name: 
      - docker
      - docker-compose
  
  - name: chmod {{ user }} -aG docker
    user:
      name: "{{ user }}"
      state: present
      groups:
      - docker
      append: yes

  - name: make dns dir
    file:
      path: /opt/Mr-Labkit/bind
      state: directory

  # ここだけ変える
  - name: copy dir
    copy:
      src: "{{ item }}"
      dest: /opt/Mr-Labkit/bind
    with_fileglob:
    - "bind/master/*"

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/bind/
      state: present
