---
- hosts: client
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install NFS
    apt:
      name: nfs-common
      state: latest
  
  - name: mount
    mount:
      src: ldap-server:/home
      path: /home
      fstype: nfs
      state: mounted
