---
- hosts: all
  gather_facts: true
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install sssd
    apt:
      name: 
      - sssd-ldap
      state: latest

  # 設定ファイルの適用
  - name: add hosts
    shell: echo {{ serverip }} ldap-server >> /etc/hosts
  
  - name: configure sssd
    copy:
      src: sssd/sssd.conf
      dest: /etc/sssd/sssd.conf
  
  - name: 
    file: 
      path: /etc/sssd/sssd.conf
      mode: '0600'
  
  - name: restart sssd
    service:
      name: sssd
      state: restarted
      enabled: true
  
  - name: auto make home dir
    command: pam-auth-update --enable mkhomedir