- hosts: revproxy
  gather_facts: yes
  remote_user: "{{ user }}"
  vars_files:
  - vars.yml

  tasks:
  - name: install package
    apt:
      name: 
      - docker
      - docker-compose
  
  - name: chmod {{ user }} -aG docker
    user:
      name: "{{ user }}"
      state: present
      groups:
      - docker
      append: yes

  - name: make docker dir
    file:
      path: /opt/Mr-Labkit/nginx
      state: directory

  - name: copy dir
    copy:
      src: nginx
      dest: /opt/Mr-Labkit

  - name: build nginx image
    shell: docker build -t nginx . --network host chdir=/opt/Mr-Labkit/nginx/

  - name: docker compose
    docker_compose:
      project_src: /opt/Mr-Labkit/nginx/
      state: present