Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.ssh.guest_port = 22
    config.ssh.username = "vagrant"
    config.vm.provider "libvirt" do |lv|
        lv.memory = "8192"
        lv.cpus = 4
    end

    config.vm.define :s1 do |server|
        server.vm.hostname = "s1"
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "192.168.122.11"
    end

    (0..2).each do |i|
        config.vm.define "c#{i}" do |host|
            host.vm.hostname = "c#{i}"
            host.vm.network :public_network, 
               :dev => "virbr0",
               :mode => "bridge",
               :type => "bridge",
               :ip => "192.168.122.#{i}"
        end
    end
end