Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.ssh.guest_port = 22
    config.ssh.username = "vagrant"
    config.vm.provider "libvirt" do |lv|
        lv.memory = "8192"
        lv.cpus = 4
    end
    
    config.vm.define :s1 do |server|
        server.vm.hostname = "s1"
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "192.168.122.11"
    end
     
    config.vm.define :c1 do |server|
        server.vm.hostname = "c1"
        server.vm.network :public_network, 
            :dev => "virbr0",
            :mode => "bridge",
            :type => "bridge",
            :ip => "192.168.122.12"
    end 
end